### PR TITLE
Feat: Skip event if theres no listener

### PR DESCRIPTION
**Pull request by WafflesAreCool131**

### CODE REVIEW

**Comment by WafflesAreCool131** [comment]
release failed lol

**Comment by lezetho** [comment]
Failed @WafflesAreCool131 . Will be awaiting a successful test.

**Comment by WafflesAreCool131** [comment]
it failed release

**Comment by Pancaksee** [comment]
damn workflow broke on you

**Comment by Pancaksee** [comment]
Declined No  Need For Graphene Patches while we got a excessive amount of lithium

**Pull request closed without merging**
